export type ProjectLink = {
  label: string;
  href: string;
};

export type PortfolioProject = {
  id: string;
  title: string;
  description: string;
  tags: string[];
  image: string;
  links: ProjectLink[];
};

export type AppGalleryItem = {
  id: string;
  title: string;
  description: string;
  tags: string[];
  href: string;
};

// Central source of truth for projects used across pages.
export const portfolioProjects: PortfolioProject[] = [
  {
    id: "autonomous-ai-agent-researcher",
    title: "Autonomous AI Agent Researcher",
    description:
      "An end-to-end AI research assistant that takes a problem, proposes hypotheses, runs experiments, and produces research outputs.",
    tags: ["AI", "Research", "Automation"],
    image: "https://res.cloudinary.com/dadnrpnid/image/upload/v1770615297/ai_Resraercher_zjj10d.png",
    links: [],
  },
  {
    id: "tourci",
    title: "TourCI",
    description:
      "TourCI is the #2 tourism app in Cote d'Ivoire. It helps users discover places and explore them in 360.",
    tags: ["Tourism", "Mobile", "360"],
    image: "https://www.tour.ci/images/logo.png",
    links: [
      {
        label: "Website",
        href: "https://www.tour.ci/",
      },
    ],
  },
  {
    id: "help-ai",
    title: "Help AI",
    description:
      "An open-source Python project using GPT-3/GPT-4 and LangChain to build a customer-service AI agent, with company help-center data vectorized in Pinecone.",
    tags: ["Python", "OpenAI", "LangChain", "Pinecone"],
    image: "https://res.cloudinary.com/dadnrpnid/image/upload/v1770615655/Gemini_Generated_Image_wy5yecwy5yecwy5y_iprjeu.png",
    links: [
      {
        label: "GitHub",
        href: "https://github.com/Salomondiei08/HelpAI",
      },
    ],
  },
];

export const featuredProjectId = "autonomous-ai-agent-researcher";

export const featuredProject =
  portfolioProjects.find((project) => project.id === featuredProjectId) ?? portfolioProjects[0];

export const appGalleryItems: AppGalleryItem[] = [
  {
    id: "phone-price-comparator",
    title: "Phone Price Comparator",
    description: "Scrapes e-commerce websites worldwide to compare phone prices.",
    tags: ["Web Scraping", "E-commerce"],
    href: "http://pricescrapper.reinvent-labs.com/",
  },
  {
    id: "gemini-watermark-remover",
    title: "Gemini Watermark Remover",
    description: "Removes the Gemini watermark from images generated by Gemini.",
    tags: ["Image Processing", "AI"],
    href: "http://geminiremove.reinvent-labs.com/",
  },
  {
    id: "link-previewer",
    title: "Link Previewer",
    description: "Previews links and displays the content of their meta tags.",
    tags: ["Metadata", "Web Tools"],
    href: "https://linkpreviewer.reinvent-labs.com/",
  },
  {
    id: "autoemail",
    title: "AutoEmail",
    description: "Sends emails in bulk through a simple automation workflow.",
    tags: ["Email", "Automation"],
    href: "https://automail.reinvent-labs.com/",
  },
];
